id: 'climate_control_for_two_windows_in_Sophies_room'
alias: sophie turn on heating in sophies room in Sophie's room
description: Turn off heating when either window is open and turn it back on when both windows are closed
trigger:
  - platform: state
    entity_id:
      - binary_sensor.sophie_sensor_sophievindue1_contact
      - binary_sensor.sophie_sensor_sophievindue2_contact
condition: []
action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.sophie_sensor_sophievindue1_contact
                state: 'on'
              - condition: state
                entity_id: binary_sensor.sophie_sensor_sophievindue2_contact
                state: 'on'
        sequence:
          - service: climate.turn_off
            target:
              entity_id: climate.sophies_vaerelse
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.sophie_sensor_sophievindue1_contact
                state: 'off'
              - condition: state
                entity_id: binary_sensor.sophie_sensor_sophievindue2_contact
                state: 'off'
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.sophies_vaerelse
            data:
              hvac_mode: auto
mode: single