- id: alarm_trigger_away
  alias: Alarm Trigger Alarm While Armed Away
  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_30, binary_sensor.openclose_31
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.aeblevangen_alarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.aeblevangen_alarm
# - id: '1588851878906'
#   alias: Alarm Sluk Alt Lys Naar Alarm Tilkobles
#   description: ''
#   trigger:
#   - entity_id: alarm_control_panel.aeblevangen_alarm
#     from: disarmed
#     platform: state
#     to: armed_away
#   condition: []
#   action:
#   - scene: scene.slukaltlys
