- id: '1697148780977'
  alias: Stue åben lille vindue gardin
  description: ''
  triggers:
  - device_id: aa35a6a04f3fcff0fcfe53fa9a61973b
    domain: deconz
    type: remote_button_short_press
    subtype: open
    trigger: device
  conditions: []
  actions:
  - data: {}
    action: cover.open_cover
    target:
      device_id: e7a3970603bbf5f1e64e13b435e134ef
  mode: single
- id: '1697148849703'
  alias: stue luk lille vindue gardin
  description: ''
  triggers:
  - device_id: aa35a6a04f3fcff0fcfe53fa9a61973b
    domain: deconz
    type: remote_button_short_press
    subtype: close
    trigger: device
  conditions: []
  actions:
  - data: {}
    action: cover.close_cover
    target:
      device_id: e7a3970603bbf5f1e64e13b435e134ef
  mode: single
- id: '1697148849415'
  alias: Trine er kommet hjem - Frederik
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.trine_haase_pedersen
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_frederik_iphone_15_pro
    data:
      message: Trine er kommet hjem
- id: '1697148849515'
  alias: Trine er kommet hjem - Sophie
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.trine_haase_pedersen
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_sophie_iphone
    data:
      message: Mor er kommet hjem
- id: '1697148849615'
  alias: Trine er kommet hjem - Victoria
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.trine_haase_pedersen
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_iphone_4
    data:
      message: Mor er kommet hjem
- id: '1697148849715'
  alias: Trine er kommet hjem - Tristan
  description: ''
  triggers:
  - entity_id:
    - person.trine_haase_pedersen
    from: not_home
    to: home
    trigger: state
  actions:
  - action: notify.mobile_app_tristan_iphone_13
    data:
      message: Mor er kommet hjem
- id: '2697148849715'
  alias: Frederik er kommet hjem - Frederik
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.frederik_kristian_pedersen
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_frederik_iphone_15_pro
    data:
      message: Jeg er kommet hjem
- id: '2697148849615'
  alias: Frederik er kommet hjem - Victoria
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.frederik_kristian_pedersen
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_iphone_4
    data:
      message: Far er kommet hjem
- id: '2697148849515'
  alias: Frederik er kommet hjem - Tristan
  description: ''
  triggers:
  - entity_id:
    - person.frederik_kristian_pedersen
    from: not_home
    to: home
    trigger: state
  actions:
  - action: notify.mobile_app_tristan_iphone_13
    data:
      message: Far er kommet hjem
- id: '2697148849415'
  alias: Frederik er kommet hjem - Trine
  description: ''
  triggers:
  - entity_id:
    - person.frederik_kristian_pedersen
    from: not_home
    to: home
    trigger: state
  actions:
  - action: notify.mobile_app_trine_iphone_14_pro
    data:
      message: Frederik er kommet hjem
- id: '26971488489515'
  alias: Frederik er kommet hjem - Sophie
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.frederik_kristian_pedersen
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_sophie_iphone
    data:
      message: Far er kommet hjem
- id: '3697148849415'
  alias: Sophie er kommet hjem - Frederik
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.sophie_haase_pedersen
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_frederik_iphone_15_pro
    data:
      message: Sophie er kommet hjem
- id: '3697148849515'
  alias: Sophie er kommet hjem - Trine
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.sophie_haase_pedersen
    from: not_home
    to: home
  action:
  - action: notify.mobile_app_trine_iphone_14_pro
    data:
      message: Sophie er kommet hjem
- id: '3697148849615'
  alias: Sophie er kommet hjem - Victoria
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.sophie_haase_pedersen
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_iphone_4
    data:
      message: Sophie er kommet hjem
- id: '3697148849715'
  alias: Sophie er kommet hjem - Tristan
  description: ''
  triggers:
  - entity_id:
    - person.sophie_haase_pedersen
    from: not_home
    to: home
    trigger: state
  actions:
  - action: notify.mobile_app_tristan_iphone_13
    data:
      message: Sophie er kommet hjem
- id: '4697148849415'
  alias: Victoria er kommet hjem - Frederik
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.victoria_haase_pedersen
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_frederik_iphone_15_pro
    data:
      message: Victoria er kommet hjem
- id: '4697148849515'
  alias: Victoria er kommet hjem - Trine
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.victoria_haase_pedersen
    from: not_home
    to: home
  action:
  - action: notify.mobile_app_trine_iphone_14_pro
    data:
      message: Victoria er kommet hjem
- id: '4697148849615'
  alias: Victoria er kommet hjem - Sophie
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.victoria_haase_pedersen
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_sophie_iphone
    data:
      message: Victoria er kommet hjem
- id: '4697148849715'
  alias: Victoria er kommet hjem - Tristan
  description: ''
  triggers:
  - entity_id:
    - person.victoria_haase_pedersen
    from: not_home
    to: home
    trigger: state
  actions:
  - action: notify.mobile_app_tristan_iphone_13
    data:
      message: Victoria er kommet hjem
- id: '5697148849415'
  alias: Tristan er kommet hjem - Frederik
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.tristan
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_frederik_iphone_15_pro
    data:
      message: Tristan er kommet hjem
- id: '5697148849515'
  alias: Tristan er kommet hjem - Trine
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.tristan
    from: not_home
    to: home
  action:
  - action: notify.mobile_app_trine_iphone_14_pro
    data:
      message: Tristan er kommet hjem
- id: '5697148849615'
  alias: Tristan er kommet hjem - Sophie
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.tristan
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_sophie_iphone
    data:
      message: Tristan er kommet hjem
- id: '5697148849715'
  alias: Tristan er kommet hjem - Victoria
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.tristan
    from: not_home
    to: home
  action:
  - service: notify.mobile_app_iphone_4
    data:
      message: Tristan er kommet hjem
- id: '1721776282506'
  alias: Sophie er kommet hjem TTS
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.sophie_iphone
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.aben_lukke
      message: Sophie er kommet hjem
      language: da-DK
  mode: single
- id: '1721777352759'
  alias: Trine er kommet hjem TTS
  description: ''
  trigger:
  - platform: zone
    entity_id: person.trine_haase_pedersen
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.aben_lukke
      message: Mor er kommet hjem
      language: da-DK
  mode: single
- id: '1721778388939'
  alias: Victoria er kommet hjem TTS
  description: resume playing after TTS
  trigger:
  - platform: zone
    entity_id: person.victoria_haase_pedersen
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.aben_lukke
      message: Victoria er kommet hjem
      language: da-DK
  mode: single
- id: '1721778520182'
  alias: Tristan er kommet hjem TTS
  description: Resume playing after TTS
  trigger:
  - platform: zone
    entity_id: person.tristan
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.aben_lukke
      message: Tristan er kommet hjem
      language: da-DK
  mode: single
- id: '1721778585916'
  alias: Frederik er kommet hjem TTS
  description: Resume playing after TTS
  trigger:
  - platform: zone
    entity_id: person.frederik_kristian_pedersen
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.aben_lukke
      message: Far er kommet hjem
      language: da-DK
  mode: single
- id: '1721779087759'
  alias: Stue stor terrassedør åbnet TTS
  description: resume playing after TTS
  triggers:
  - type: opened
    device_id: 3b71e11b51fa44389b96f86d03f07692
    entity_id: c09dcd2007eb746a94b12f397f155f5a
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - metadata: {}
    data:
      entity_id: media_player.aben_lukke
      message: Terrassedøren i stuen er blevet åbnet
      language: da-DK
    action: tts.cloud_say
  mode: single
- id: '1721779415086'
  alias: 'Bryggers døren er blevet åbnet '
  description: resume playing after TTS
  triggers:
  - type: opened
    device_id: fbdccd24e03ffc66c22b8fe9767c9889
    entity_id: cdaa7e29c83160b5a3848c45f6147a08
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - metadata: {}
    data:
      cache: true
      entity_id: media_player.aben_lukke
      message: Bryggersdøren er blevet åbnet
      language: da-DK
    action: tts.cloud_say
  mode: single
- id: '1722303039761'
  alias: Frederik Husk at købe
  description: ''
  trigger:
  - platform: zone
    entity_id: person.frederik_kristian_pedersen
    zone: zone.rema1000
    event: enter
  - platform: zone
    entity_id: person.frederik_kristian_pedersen
    zone: zone.fotex
    event: enter
  - platform: zone
    entity_id: person.frederik_kristian_pedersen
    zone: zone.coop_365_hasseris
    event: enter
  - platform: zone
    entity_id: person.frederik_kristian_pedersen
    zone: zone.handel_netto_hasseris
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_frederik_iphone_15_pro
    metadata: {}
    data:
      message: Husk og købe disse vare
      title: Tryk her
      data:
        clickAction: /Huskelister
        url: /todo?entity_id=todo.indkobsliste
  mode: single
- id: '1722303277292'
  alias: Trine Husk at købe
  description: ''
  trigger:
  - platform: zone
    entity_id: person.trine_haase_pedersen
    zone: zone.rema1000
    event: enter
  condition: []
  action:
  - action: notify.mobile_app_trine_iphone_14_pro
    data:
      data:
        clickAction: /Huskelister
        url: /todo?entity_id=todo.indkobsliste
      title: Tryk her
      message: Husk og købe disse vare
  mode: single
- id: '1722349301296'
  alias: 'Trine - Husk at købe '
  description: ''
  trigger:
  - platform: zone
    entity_id: person.trine_haase_pedersen
    zone: zone.rema1000
    event: enter
  - platform: zone
    entity_id: person.trine_haase_pedersen
    zone: zone.fotex
    event: enter
  - platform: zone
    entity_id: person.trine_haase_pedersen
    zone: zone.coop_365_hasseris
    event: enter
  - platform: zone
    entity_id: person.trine_haase_pedersen
    zone: zone.handel_netto_hasseris
    event: enter
  condition: []
  action:
  - action: notify.mobile_app_trine_iphone_14_pro
    data:
      data:
        clickAction: /Huskelister
        url: /todo?entity_id=todo.indkobsliste
      message: Husk og købe disse vare
      title: Tryk her
  mode: single
- id: '1722632708446'
  alias: Sophie - Over Skrivebord - Tænd/sluk/skru op og ned
  description: ''
  use_blueprint:
    path: poolcactus/zha-ikea-tradfri-on-off-switch-incl-dimmer.yaml
    input:
      remote: 6f3a31e6229bef05fc6f54a4be47e0f2
      light:
        device_id: e659d2f909a0febbf86d7274a75cac2f
- id: '1722633011461'
  alias: Sophie - over seng - Tænd/sluk/skru op og ned
  description: ''
  use_blueprint:
    path: poolcactus/zha-ikea-tradfri-on-off-switch-incl-dimmer.yaml
    input:
      remote: cffb04466beb286dbf83a2d889fb92a3
      light:
        device_id: dcd8efa4c4f2b0b26b25634fa2d773f0
- id: '1727648335717'
  alias: Legestue - sluk TV efter kl 2200
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      device_id: c9e17d5fef2b455565f01cf5cb1c3a72
  mode: single
- id: '1727648397425'
  alias: Legestue - tænd TV efter kl 0600
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition: []
  action:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      device_id: c9e17d5fef2b455565f01cf5cb1c3a72
  mode: single
- id: '1734222859007'
  alias: 'Stue - Tænd for lille lampe ved tv når loft lys "stuesofa" tænder '
  description: ''
  triggers:
  - type: turned_on
    device_id: 04bb7f2a1f6a2eae765a35c2019b9de3
    entity_id: 8a374da779d4b3ce0bb66a5cfae5c00d
    domain: light
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: 97fa7024552e0b30df6473be1129dadd
    entity_id: 62a0859166b131d5a113460522ec7cf4
    domain: switch
  mode: single
- id: '1734222939492'
  alias: 'Stue - sluk for lille lampe ved tv når loft lys "stuesofa" slukker '
  description: ''
  triggers:
  - type: turned_off
    device_id: 04bb7f2a1f6a2eae765a35c2019b9de3
    entity_id: 8a374da779d4b3ce0bb66a5cfae5c00d
    domain: light
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: 97fa7024552e0b30df6473be1129dadd
    entity_id: 62a0859166b131d5a113460522ec7cf4
    domain: switch
  mode: single
- id: '1734593887463'
  alias: Kontor - vindue åben
  description: Luk Radiator når vinduet åbnes
  triggers:
  - type: opened
    device_id: 6685d2781c1b97e3227e8ddb4f0a9387
    entity_id: 723e8118874603457d5746b52aa633f1
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: 'off'
    target:
      device_id: 70031b73bebd812285d08297d6d4cd38
  mode: single
- id: '1734593961335'
  alias: Kontor - vindue åben
  description: Sæt Radiator til auto når vinduet Lukkes
  triggers:
  - type: not_opened
    device_id: 6685d2781c1b97e3227e8ddb4f0a9387
    entity_id: 723e8118874603457d5746b52aa633f1
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: auto
    target:
      device_id: 70031b73bebd812285d08297d6d4cd38
  mode: single
- id: '1734597133659'
  alias: Victoria - Sluk lys over skrivebord
  description: ''
  triggers:
  - domain: mqtt
    device_id: ee80491d05cdc82c945f934c9d10959c
    type: action
    subtype: 'on'
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: 06be6bef03a012d7624afd861b571b1c
    entity_id: d7c4891e4d2161fd14e8b14b2b1ca215
    domain: light
  mode: single
- id: '1734597244090'
  alias: Victoria - Tænd lys over skrivebord
  description: ''
  triggers:
  - domain: mqtt
    device_id: ee80491d05cdc82c945f934c9d10959c
    type: action
    subtype: 'on'
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: 06be6bef03a012d7624afd861b571b1c
    entity_id: d7c4891e4d2161fd14e8b14b2b1ca215
    domain: light
  mode: single
- id: '1734598816455'
  alias: Victoria - Sluk lys over seng
  description: ''
  triggers:
  - domain: mqtt
    device_id: dada718125fa62aec93f4ab10de045ea
    type: action
    subtype: 'off'
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: cb03b6e9dc646b7a226b5b7ee67c5d50
    entity_id: 330393822a88b56289a8ee40681dbe15
    domain: light
  mode: single
- id: '1734598856287'
  alias: Victoria - Tænd lys over seng
  description: ''
  triggers:
  - domain: mqtt
    device_id: dada718125fa62aec93f4ab10de045ea
    type: action
    subtype: 'on'
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: cb03b6e9dc646b7a226b5b7ee67c5d50
    entity_id: 330393822a88b56289a8ee40681dbe15
    domain: light
  mode: single
- id: '1734680525144'
  alias: Kontor - Tænd lys
  description: ''
  triggers:
  - domain: mqtt
    device_id: 9d40a6d3b1d108acd0092f707f339bf0
    type: action
    subtype: arrow_left_click
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: fd90a586a8931bbd1473e8b512253b43
    entity_id: edcd586a475c35e5ada40fdc6fa6dd7e
    domain: light
  mode: single
- id: '1734680554585'
  alias: Kontor - Sluk lys
  description: ''
  triggers:
  - domain: mqtt
    device_id: 9d40a6d3b1d108acd0092f707f339bf0
    type: action
    subtype: arrow_right_click
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: fd90a586a8931bbd1473e8b512253b43
    entity_id: edcd586a475c35e5ada40fdc6fa6dd7e
    domain: light
  mode: single
- id: '1734680599895'
  alias: Baghave - Tænd/sluk
  description: ''
  triggers:
  - domain: mqtt
    device_id: 9d40a6d3b1d108acd0092f707f339bf0
    type: action
    subtype: brightness_up_click
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: b15e53728be37e4ae307509b4bbed905
    entity_id: ed48ca70f647f9eac01ebbefb009c1cd
    domain: switch
  mode: single
