
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
