homeassistant:
  whitelist_external_dirs:
    - /tmp
  # Name of the location where Home Assistant is running
  name: !secret HomeAssistantName
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  # Customization file
  customize: !include customize.yaml
    # binary_sensor.floorplan:
      # custom_ui_state_card: state-card-floorplan
      # config: !include floorplan.yaml

#System Health
system_health:

# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html

# If you change the name of your floorplan.svg file, change it here too.
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan 
    config: !include floorplan.yaml
    
# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Kamera
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# android_ip_webcam:
  # - host: 192.168.1.86
    # port: 8080
    # sensors:
      # - audio_connections
      # - battery_level
      # - battery_temp
      # - battery_voltage
      # - light
      # - motion
      # - pressure
      # - proximity
      # - sound
      # - video_connections
    # switches:
      # - exposure_lock
      # - ffc
      # - focus
      # - gps_active
      # - night_vision
      # - overlay
      # - torch
      # - whitebalance_lock
      # - video_recording

# stream:

# camera:
  # - platform: generic
    # #still_image_url: http://192.168.1.60/jpg/image.jpg
    # stream_source: http://192.168.1.60/video1.mjpg

# Sensors
sensor:
  # Weather
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
      
  # MQTT extracting Wavin current temperatur from all the topics   
  - platform: mqtt
    name: "LilleWCFordoer"
    state_topic: "heat/floor807D3A790941/0/current"
  - platform: mqtt
    name: "BryggersVarme"
    state_topic: "heat/floor807D3A790941/1/current"
  - platform: mqtt
    name: "KøkkenVarme"
    state_topic: "heat/floor807D3A790941/2/current"
  - platform: mqtt
    name: "StorWCVarme"
    state_topic: "heat/floor807D3A790941/3/current"
  - platform: mqtt
    name: "GangVarme"
    state_topic: "heat/floor807D3A790941/4/current"
  - platform: mqtt
    name: "TristansVarme"
    state_topic: "heat/floor807D3A790941/5/current"
      
  # travis
  - platform: travisci
    api_key: !secret travis_token

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

#Sonoff
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  scan_interval: 60 #(optional, lower values than 60 won't work anymore!)
  grace_period: 600 #(optional)
  api_region: 'eu' #(optional)
  entity_prefix: True #(optional)
  debug: False #(optional)

#MQTT 
mqtt:
  discovery: false
  discovery_prefix: homeassistant
  broker: !secret mqqt_ip
  port: !secret mqqt_port
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password

#Philips Hue
hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true
      allow_hue_groups: true

#Led strips 
light:
  - platform: flux_led
    devices:
      192.168.3.62:
        name: under_koekkenbordet
      # 192.168.3.61:
      #   name: kontor_led

# Verisure setup configuration
verisure:
    username: !secret verisure_username
    password: !secret verisure_password

#Temperature in our house (Tado)
tado:
    username: !secret tado_username
    password: !secret tado_password

#Tracking who is home or out (not on WiFi)
device_tracker:
  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: 255063
  - platform: nmap_tracker 
    #Witch devices to track
    hosts:
       #Frederik
       - !secret frederikMobilNmap
       #Trine
       - !secret trineMobilNmap
       #Sophie
       - !secret sophieMobilNmap
    #How many seconds between scans 
    home_interval: 10
    #How long (in seconds) before a device is considered not home. This helps prevent false readings
    consider_home: 180
    #Find and track new devices 
    new_device_defaults:
      track_new_devices: true

#Scenes
scene:
  - name: Livingroom normal
    entities:
      light.stue_1:
        state: on
        transition: 2
        brightness_pct: 100
      light.stue_2:
        state: on
        transition: 2
        brightness_pct: 100
  - name: Livingroom dim
    entities:
      light.stue_1:
        state: on
        transition: 2
        brightness_pct: 30
      light.stue_2:
        state: on
        transition: 2
        brightness_pct: 30

#Lille WC
climate wavinAhc9000_1:
  - platform: mqtt
    name: LilleWCFordoerVarme
    current_temperature_topic: "heat/floor807D3A790941/0/current"
    temperature_command_topic: "heat/floor807D3A790941/0/target_set"
    temperature_state_topic: "heat/floor807D3A790941/0/target"
    mode_command_topic: "heat/floor807D3A790941/0/mode_set"
    mode_state_topic: "heat/floor807D3A790941/0/mode"
    modes:
    - "heat"
    - "off"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    qos: 0

sensor wavinBattery1:
  - platform: mqtt
    state_topic: "heat/floor807D3A790941/0/battery"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    name: LilleWCBatt
    unit_of_measurement: "%"
    device_class: battery
    qos: 0

#Bryggers
climate wavinAhc9000_2:
  - platform: mqtt
    name: BryggersVarme
    current_temperature_topic: "heat/floor807D3A790941/1/current"
    temperature_command_topic: "heat/floor807D3A790941/1/target_set"
    temperature_state_topic: "heat/floor807D3A790941/1/target"
    mode_command_topic: "heat/floor807D3A790941/1/mode_set"
    mode_state_topic: "heat/floor807D3A790941/1/mode"
    modes:
    - "heat"
    - "off"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    qos: 0

sensor wavinBattery2:
  - platform: mqtt
    state_topic: "heat/floor807D3A790941/1/battery"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    name: BryggersBatt
    unit_of_measurement: "%"
    device_class: battery
    qos: 0

#Køkken
climate wavinAhc9000_3:
  - platform: mqtt
    name: KøkkenVarme
    current_temperature_topic: "heat/floor807D3A790941/2/current"
    temperature_command_topic: "heat/floor807D3A790941/2/target_set"
    temperature_state_topic: "heat/floor807D3A790941/2/target"
    mode_command_topic: "heat/floor807D3A790941/2/mode_set"
    mode_state_topic: "heat/floor807D3A790941/2/mode"
    modes:
    - "heat"
    - "off"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    qos: 0
    
sensor wavinBattery3:
  - platform: mqtt
    state_topic: "heat/floor807D3A790941/2/battery"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    name: KøkkenBatt
    unit_of_measurement: "%"
    device_class: battery
    qos: 0

#Stor WC
climate wavinAhc9000_4:
  - platform: mqtt
    name: StorWCVarme
    current_temperature_topic: "heat/floor807D3A790941/3/current"
    temperature_command_topic: "heat/floor807D3A790941/3/target_set"
    temperature_state_topic: "heat/floor807D3A790941/3/target"
    mode_command_topic: "heat/floor807D3A790941/3/mode_set"
    mode_state_topic: "heat/floor807D3A790941/3/mode"
    modes:
    - "heat"
    - "off"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    qos: 0
    
sensor wavinBattery4:
  - platform: mqtt
    state_topic: "heat/floor807D3A790941/3/battery"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    name: StorWCBatt
    unit_of_measurement: "%"
    device_class: battery
    qos: 0

#Gang
climate wavinAhc9000_5:
  - platform: mqtt
    name: GangVarme
    current_temperature_topic: "heat/floor807D3A790941/4/current"
    temperature_command_topic: "heat/floor807D3A790941/4/target_set"
    temperature_state_topic: "heat/floor807D3A790941/4/target"
    mode_command_topic: "heat/floor807D3A790941/4/mode_set"
    mode_state_topic: "heat/floor807D3A790941/4/mode"
    modes:
    - "heat"
    - "off"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    qos: 0
    
sensor wavinBattery5:
  - platform: mqtt
    state_topic: "heat/floor807D3A790941/4/battery"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    name: GangBatt
    unit_of_measurement: "%"
    device_class: battery
    qos: 0

#Tristans Værelse
climate wavinAhc9000_6:
  - platform: mqtt
    name: TristansVarme
    current_temperature_topic: "heat/floor807D3A790941/5/current"
    temperature_command_topic: "heat/floor807D3A790941/5/target_set"
    temperature_state_topic: "heat/floor807D3A790941/5/target"
    mode_command_topic: "heat/floor807D3A790941/5/mode_set"
    mode_state_topic: "heat/floor807D3A790941/5/mode"
    modes:
    - "heat"
    - "off"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    qos: 0
    
sensor wavinBattery6:
  - platform: mqtt
    state_topic: "heat/floor807D3A790941/5/battery"
    availability_topic: "heat/floor807D3A790941/online"
    payload_available: "True"
    payload_not_available: "False"
    name: TristansBatt
    unit_of_measurement: "%"
    device_class: battery
    qos: 0

#include Gruoups
group: !include groups.yaml
#include Automations
automation: !include automations.yaml
#include Scripts
script: !include scripts.yaml