# Sensors
# Weather
- platform: yr
  name: Weather
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

- platform: darksky
  api_key: !secret darksky
  name: Weather
  units: si
  forecast: 1
  monitored_conditions:
    - temperature
    - apparent_temperature
    - temperature_min
    - temperature_max
    - humidity
    - precip_probability
    - precip_intensity
    - precip_type
    - wind_speed
    - wind_bearing
    - pressure
    - icon

################################################################
#                                                              #
# MQTT extracting Wavin current temperatur from all the topics #
#                                                              #
################################################################
  # 
- platform: mqtt
  name: "LilleWCFordoer"
  state_topic: "heat/floor807D3A790941/0/current"
- platform: mqtt
  name: "BryggersVarme"
  state_topic: "heat/floor807D3A790941/1/current"
- platform: mqtt
  name: "KøkkenVarme"
  state_topic: "heat/floor807D3A790941/2/current"
- platform: mqtt
  name: "StorWCVarme"
  state_topic: "heat/floor807D3A790941/3/current"
- platform: mqtt
  name: "GangVarme"
  state_topic: "heat/floor807D3A790941/4/current"
- platform: mqtt
  name: "TristansVarme"
  state_topic: "heat/floor807D3A790941/5/current"            

#==============================
#=== Installed version
#==============================
- platform: command_line
  name: Current Version
  command: "cat /home/homeassistant/.homeassistant/.HA_VERSION"
#================================

#==============================
#=== Lasetes stable version on github
#==============================
- platform: rest
  resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
  username: !secret github_username
  password: !secret github_password
  authentication: basic
  value_template: '{{ value_json.tag_name }}'
  headers:
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor
  name: Lastest Release

- platform: rest
  resource: http://ip.jsontest.com
  name: External IP
  value_template: '{{ value_json.ip }}'

####################################################
#                                                  #
#                 SYSTEM MONITOR                   #
#                                                  #
####################################################

#https://home-assistant.io/components/sensor.systemmonitor/
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: command_line
  name: internal_ip
  command: "hostname -I"

# CPU Temp
- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(2)  }}'

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################