views:
  - title: main
    icon: mdi:home-outline
    cards:
    
#
################
#### Indkøb ####
################
#

    
#
###############
#### Klima ####
###############
#

  - title: Climate
    icon: mdi:thermometer-lines
    cards:
      - type: thermostat
        entity: climate.sovevrelse
      - type: thermostat
        entity: climate.kontor
      - type: thermostat
        entity: climate.stue_2
      - type: thermostat
        entity: climate.stue
      - type: thermostat
        entity: climate.lege_stue
      - type: thermostat
        entity: climate.sophies_vrelse
      - type: thermostat
        entity: climate.victorias_vrelse
      - type: sensor
        entity: sensor.gang_temperature
      - type: sensor
        entity: sensor.kkken_temperature
      - type: sensor
        entity: sensor.bryggers_temperature 
      
    
    
#
####################
#### FLOOR PLAN ####
####################
#
  - title: Floor plan
    panel: true
    cards:
      - type: picture-elements
        image: /local/floorPlan.png
        elements:
        #### Lys ####
        #### Garage ####
          - type: state-icon
            title: Legestue 1
            tap_action: toggle
            entity: light.dimmable_light_1
            style:
              top: 36%
              left: 35%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
          - type: state-icon
            title: Legestue 2
            tap_action: toggle
            entity: light.color_light_1
            style:
              top: 44%
              left: 44%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
          - type: state-icon
            title: Legestue 3
            tap_action: toggle
            entity: light.dimmable_light_1_4
            style:
              top: 44%
              left: 35%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
        #### Garage ####
          - type: state-icon
            title: Garage
            tap_action: toggle
            entity: light.dimmable_light_1_3
            style:
              top: 5%
              left: 97%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
          - type: state-icon
            title: Bag dør
            tap_action: toggle
            entity: light.dimmable_light_1_2
            style:
              top: 50%
              left: 93%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
        #### Kontor ####
          - type: state-icon
            title: Kontor LED
            tap_action: toggle
            entity: light.kontor_led
            style:
              top: 10%
              left: 85%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
        #### Badevaerelse ####
          - type: state-icon
            title: Badeværelse
            tap_action: toggle
            entity: light.badevrelse_2
            style:
              top: 23%
              left: 80%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
        #### Sovevaerelse ####
          - type: state-icon
            title: Soveværelse
            tap_action: toggle
            entity: light.sovevrelse_2
            style:
              top: 16%
              left: 58%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
        #### Gang ####
          - type: state-icon
            title: Gang 1
            tap_action: toggle
            entity: light.gang_1
            style:
              top: 23%
              left: 70%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
          - type: state-icon
            title: Gang 2
            tap_action: toggle
            entity: light.gang_2
            style:
              top: 33%
              left: 70%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
        #### Tristans Vaerelse ####      
          - type: state-icon
            title: Tristans værelse
            tap_action: toggle
            entity: light.tristans_vrelse
            style:
              top: 33%
              left: 58%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
        #### Stue ####      
          - type: state-icon
            title: Stue 1
            tap_action: toggle
            entity: light.stue_1
            style:
              top: 52%
              left: 62%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
          - type: state-icon
            title: Stue 2
            tap_action: toggle
            entity: light.stue_2
            style:
              top: 75%
              left: 62%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
        #### Koekken ####  
          - type: state-icon
            title: Under køkkenbordet
            tap_action: toggle
            entity: light.under_koekkenbordet
            style:
              top: 48%
              left: 78%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
          - type: state-icon
            title: Køkken 1
            tap_action: toggle
            entity: light.kkken_1
            style:
              top: 58%
              left: 76%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
          - type: state-icon
            title: Køkken 2
            tap_action: toggle
            entity: light.kkken_2
            style:
              top: 58%
              left: 88%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
        #### Spisebord ####
          - type: state-icon
            title: Spisebord
            tap_action: toggle
            entity: light.spisebord
            style:
              top: 76%
              left: 83%
              --iron-icon-height: 42px
              --iron-icon-width: 42px
        
              