alias: Turn on gang light when there is movement at nighttime
id: turn_on_gang_light_when_there_is_movement_at_nighttime
trigger:
  platform: state
  entity_id: binary_sensor.sensor_gang_philips
  to: 'on'
trigger:
  platform: sun
  event: sunset
  offset: "-00:30:00"
# condition:
# - condition: time
#   after: '22:00:00'
#   before: 06:00:00
action:
  service: scene.turn_on
  entity_id: scene.GangNat