alias: BadevaerelseDag
id: badevaerelseDag
trigger:
- platform: state
  entity_id:
  - light.badevaerelse1
  - light.badevaerelse2
  to: 'on'
  from: 'off'
condition:
- condition: time
  after: 06:00:01
  before: '18:59:59'
action:
  service: scene.turn_on
  entity_id: scene.BadevaerelseDag