#################################################################################################################
#                                                                                                               #
#                                           Eloverblik                                                          #
#                        Take the date from one of the "Eloverblik" sensors                                     #
#                                                                                                               #
#################################################################################################################

#husk date/time domain godtager ikke længere unit_of_measurement: 'date' i en template. 
- platform: template
  sensors:
    eloverbliktildato:
      unique_id: "Eloverbliktildato"
      friendly_name: "Eloverbliktildato"
      value_template: "{{ state_attr('sensor.eloverblik_energy_0_1', 'metering_date') }}"

################################################################################################################
#                                                                                                              #
#                                                Heat                                                          #
#                                                                                                              #
################################################################################################################



################################################################################################################
#                                                                                                              #
#                                              Weather                                                         #
#                                                                                                              #
################################################################################################################

    weather_temperature:
      friendly_name: Temperature Outside
      value_template: '{{ states.weather.forecast_aeblevangen_36.attributes.temperature }}'
      unit_of_measurement: °C
      unique_id: xxxx1

################################################################################################################
#                                                                                                              #
#                                            Electricity                                                       #
#                                                                                                              #
################################################################################################################

- platform: template
  sensors:
   total_solar_power:
     #state_class: total_increasing
     device_class: power
     value_template: >-
       {{ [ states('sensor.tpj4cf806p_generated_energy_today'),
            states('sensor.rfhbcfe0pf_generated_energy_today') ]
            | map('float') | sum }}
    #  availability: >
    #    {{ not 'unavailable' in 
    #       [ states('sensor.tpj4cf806p_generated_energy_today'), 
    #         states('sensor.rfhbcfe0pf_generated_energy_today') ] }}
     friendly_name: TotalSolarPower
     unit_of_measurement: kW
     #state_class: total_increasing
     unique_id: kn4356654kj36n453lk6345lm645yugfdsiogbs

- platform: template
  sensors:
      sol_total_outpu_lige_nu:
          friendly_name: "Energi lige nu (total)"
          unit_of_measurement: 'W'
          value_template: '{{ states("sensor.tpj4cf806p_pv_output_actual") | float + states("sensor.rfhbcfe0pf_pv_output_actual") | float }}'

# - platform: template
#   sensors:
#       hvad_bruger_huset_lige_nu:
#           friendly_name: "Energi huset bruger lige nu"
#           unit_of_measurement: 'W'
#           value_template: '{{ states("sensor.tpj4cf806p_pv_output_actual") | float + states("sensor.rfhbcfe0pf_pv_output_actual") | float - states("sensor.tpj4cf806p_export_to_grid") | float - states("sensor.tpj4cf806p_battery_discharging_w") | float }}'


# - platform: template
#   sensors:
#       hvad_bruger_huset_lige_nu_slimmelezer:
#           friendly_name: "Energi huset bruger lige nu fra slimmelezer"
#           unit_of_measurement: 'W'
#           value_template: '{{ states("sensor.sensor.power_consumed") | float }}'

################################################################################################################
#                                                                                                              #
#                    Solar - Adding West and East solar production into one sensor                             #
#                                                                                                              #
################################################################################################################

- platform: template
  sensors:
      vestsiden_har_lavet_i_dag:
          friendly_name: "Vestsiden har lavet i dag"
          unit_of_measurement: 'kW'
          value_template: '{{ states("sensor.tpj4cf806p_solar_pv1_energy_today") | float + states("sensor.tpj4cf806p_solar_pv2_energy_today") | float }}'

################################################################################################################
#                                                                                                              #
#                    changing wall plug sensors to be enabled in energy dashboard                              #
#                                                                                                              #
################################################################################################################

- platform: integration
  source: sensor.bryggers_vaskemaskine_power
  name: bryggers_vaskemaskine_total
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 1

- platform: integration
  source: sensor.stuen_lille_lampe_power
  name: lille_lampe_total
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 1

- platform: integration
  source: sensor.legestue_tv_power
  name: lille_stue_tv_total
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 1

- platform: integration
  source: sensor.kokken_opvaskemaskine_power
  name: opvaskemaskine_total
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 1

- platform: integration
  source: sensor.kokken_koleskab_power
  name: køleskab_total
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 1

- platform: integration
  source: sensor.kokken_airfryer_power
  name: Airfryer_total
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 1

- platform: integration
  source: sensor.kokken_fryser_power
  name: fryser_total
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 1

- platform: integration
  source: sensor.kokken_espressomaskine_power
  name: espressomaskine_total
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 1

- platform: integration
  source: sensor.skur_power
  name: Skur_total
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 1

- platform: integration
  source: sensor.victoria_computer_power
  name: victoria_computer_total
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 1

- platform: integration
  source: sensor.it_rack_power
  name: it_rack_loft_power
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 1