esphome:
  name: wavinmqtt
  friendly_name: WavinMQTT

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "W5WiVQGIUDJW72hZkkMSzHL6rW8CmDNGLe8Ot+Bihf8="

ota:
  password: "dd10bd4dba97d23b68c30a6161073f16"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wavinmqtt Fallback Hotspot"
    password: "ixAvps79NNYn"

captive_portal:
    