substitutions:
  name: apollo-msr-2-aa0cc0
  friendly_name: Apollo MSR-2 Legestue
packages:
  ApolloAutomation.MSR-2_Factory: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2_Factory.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: RsE/XgnZPmMNh17PG61u2ZleBkzdRQEiIlYD/8SboRY=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
