homeassistant:
  enabled: true
advanced:
  network_key:
    - 161
    - 10
    - 110
    - 163
    - 103
    - 70
    - 162
    - 135
    - 157
    - 210
    - 162
    - 34
    - 111
    - 161
    - 229
    - 62
  pan_id: 22430
  ext_pan_id:
    - 24
    - 201
    - 91
    - 99
    - 78
    - 223
    - 130
    - 35
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: yeiNgoshue6koquohzohqueigh1Uejohnoophohpoo9shaeg3ThigahpohShoh4e
frontend:
  enabled: true
  port: 8099
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_e20ab905b69aed118fd67a08a8669f5d-if00-port0
  adapter: ember
device_options:
  legacy: false
devices:
  '0x84ba20fffeca7c33':
    friendly_name: Kontor_Sensor_Vindue
  '0x842e14fffe757602':
    friendly_name: Stue_Repeater_ved_stor_dør
  '0x588e81fffeafee9e':
    friendly_name: Legestue_Repeater_legestue
  '0xa49e69fffe203a70':
    friendly_name: Victoria_remote_over_skrivebord
    icon: device_icons/f1504ae638f983567e4384447325f67a.png
  '0x842e14fffe63a757':
    friendly_name: Sophie_Repeater_sophie
  '0x842e14fffe6c9453':
    friendly_name: Victoria_Repeater_victoria
  '0x84fd27fffe60e528':
    friendly_name: Stue_Repeater_lille_gardin
  '0x842e14fffe6c9aa0':
    friendly_name: Køkken_repeater_køkken
  '0x5c0272fffe8b7ba4':
    friendly_name: Kontor_repeater_kontor
  '0x842e14fffe6cb841':
    friendly_name: Lillegang_repeater_lillegang
  '0x84ba20fffec7da2e':
    friendly_name: Soveværelse_Sensor_Vindue
    icon: device_icons/7a0d11aaa26685f09d07bf0e65a78a0f.png
  '0x90fd9ffffe898295':
    friendly_name: Gang_light_gang1
  '0x90fd9ffffe86c8fb':
    friendly_name: Gang_light_gang2
  '0x881a14fffea9f089':
    friendly_name: Kontor_light_kontor1
  '0x881a14fffea9f02d':
    friendly_name: Kontor_light_kontor2
  '0x90fd9ffffe8ce6e0':
    friendly_name: Kontor_remote_kontorTest
    icon: device_icons/0bb605a453f07b8806fb5bd0288dd434.png
  '0x187a3efffe8924e7':
    friendly_name: Kontor_switch_computer
  '0x90fd9ffffe15ceaf':
    friendly_name: ' Kontor_remote_kontorVedDør'
  '0x00158d00047dd58a':
    friendly_name: Stue_sensor_storVindue
  '0x00158d00045cd936':
    friendly_name: Sophie_sensor_sophieVindue1
  '0x00158d00045cf07e':
    friendly_name: Sophie_sensor_sophieVindue2
  '0x705464fffe0aa52e':
    friendly_name: Sophie_Light_sophie1
  '0x705464fffe263b2a':
    friendly_name: Sophie_Light_sophie2
  '0x60efabfffeee9b6c':
    friendly_name: Sophie_remote_sophie1
    icon: device_icons/7146bc3333829dd31b1a37b1f83f6e01.png
  '0x705464fffe265cb8':
    friendly_name: Sophie_remote_sophie2
    icon: device_icons/7146bc3333829dd31b1a37b1f83f6e01.png
  '0x6c5cb1fffe5223d6':
    friendly_name: Victoria_Light_overSeng
  '0x90fd9ffffe6ddc96':
    friendly_name: Soveværelse_Light_soveværelse
    color_sync: true
  '0x000b57fffee8f53e':
    friendly_name: Køkken_Light_køkken1
    color_sync: false
  '0x90fd9ffffe176786':
    friendly_name: Køkken_Light_køkken2
    color_sync: false
  '0x90fd9ffffe8614b5':
    friendly_name: Køkken_remote_køkken1
  '0x90fd9ffffe0e03f8':
    friendly_name: Køkken_remote_køkken2
    icon: device_icons/0bb605a453f07b8806fb5bd0288dd434.png
  '0x842712fffe194efd':
    friendly_name: Kontor_sensor_pressent
    no_occupancy_since: []
  '0x3425b4fffe9a6087':
    friendly_name: ' Victoria_remote_over_seng'
    icon: device_icons/f1504ae638f983567e4384447325f67a.png
  '0x6c5cb1fffe609906':
    friendly_name: ' Victoria_Light_over_skrivebord'
  '0xcc86ecfffe912f36':
    friendly_name: Stue_blind_stueLilleVindue
  '0x84fd27fffe479082':
    friendly_name: Stue_remote_stueLilleVindue
  '0xd0cf5efffee6f633':
    friendly_name: terrasse_Light_terrasseForHave
    color_sync: true
  '0x881a14fffe957022':
    friendly_name: ' terrasse_Light_terrasseBagHave'
    color_sync: true
  '0x90fd9ffffe02ae12':
    friendly_name: Badeværelse_Light_badeværelse1
  '0x90fd9ffffe336f74':
    friendly_name: Badeværelse_Light_badeværelse2
  '0x000b57fffef3aade':
    friendly_name: Badeværelse_remote_badeværelse
  '0x9035eafffe463ccb':
    friendly_name: Badeværelse_sensor_badeværelse1
  '0x90fd9ffffe8b10b0':
    friendly_name: ' Soveværelse_remote_soveværelse'
  '0x000b57fffeeeea51':
    friendly_name: Tristan_Light_tristan1
    color_sync: true
  '0x000b57fffeedcd8d':
    friendly_name: Tristan_remote_tristan
  '0x90fd9ffffe90f221':
    friendly_name: Stue_Light_kommode1
  '0x90fd9ffffe70fa95':
    friendly_name: Stue_Light_kommode2
  '0x000d6ffffee82601':
    friendly_name: Stue_Light_stueSofa
    color_sync: true
  '0xd0cf5efffed8c415':
    friendly_name: Stue_Light_stueSpisebord
  '0x000b57fffe9b6863':
    friendly_name: Køkken_remote_spisebord
  '0xd0cf5efffee98a78':
    friendly_name: Legestue_Light_legestue1
  '0x90fd9ffffe64cb12':
    friendly_name: Legestue_Light_legestue2
  '0x000b57fffee66f2f':
    friendly_name: Legestue_remote_legestue1
    icon: device_icons/0bb605a453f07b8806fb5bd0288dd434.png
  '0x90fd9ffffe182127':
    friendly_name: Legestue_remote_legestue2
  '0xb43522fffe7a0d9c':
    friendly_name: Garage_Light_garage1
  '0xd0cf5efffe306707':
    friendly_name: Garage_Light_garage2
  '0x00158d00045cab46':
    friendly_name: Bryggers_sensor_bryggersDør
  '0x90fd9ffffe8c74c4':
    friendly_name: Stue_remote_stueSofa
  '0x90fd9ffffe929717':
    friendly_name: '0x90fd9ffffe929717'
  '0xd0cf5efffefba8c1':
    friendly_name: Legestue_Light_legestue3
  '0x90fd9ffffed56c36':
    friendly_name: '0x90fd9ffffed56c36'
  '0x00158d00047db9c4':
    friendly_name: Victoria_sensor_victoriaVindue1
  '0x90ab96fffea2f0f7':
    friendly_name: Stue_Spisebord_remote_Stue1
groups: {}
version: 4
